### ISSUE TITLE
"byte" vs "octet"

### ISSUE THREAD

**Issue by jedisct1** [cfrg/draft-irtf-cfrg-aegis-aead#15]
The document uses both "byte" and "octet".

Maybe we should use only "octet" everywhere.

**Comment by samuel-lucas6** [comment]
Would we change the `Byte(x)` function? I would prefer byte everywhere, but I presume octet eliminates any ambiguity. The ChaCha20-Poly1305 RFC seems to use both.

**Comment by jedisct1** [comment]
I'm not a big fan of "octet" either. Even less as a function name. But we can't assume that both terms are interchangeable, as this is not true, even today (e.g. DSPs).

Maybe we can use `byte` everywhere, and mention somewhere that thorough this document, `byte`  refers to a 8-bit  sequence? I'm not sure how/where that could be doable, but it may be worth it, no matter what the ChaChaPoly RFC did.

**Comment by samuel-lucas6** [comment]
> Maybe we can use byte everywhere, and mention somewhere that thorough this document, byte refers to a 8-bit sequence? I'm not sure how/where that could be doable, but it may be worth it

I like that idea, but I'm not sure where that would go. Could we have a sentence at the top of `Conventions and Definitions`? Kind of like the [age spec](https://github.com/C2SP/C2SP/blob/main/age.md) but after the key words bit.

**Comment by jedisct1** [comment]
Fixed in #22
