### ISSUE TITLE
Mention that AEGIS must not not used as a hash function

### ISSUE THREAD

**Issue by jedisct1** [cfrg/draft-irtf-cfrg-aegis-aead#19]
AEGIS is a very good and fast MAC, so it could be tempting to use it as a replacement for a hash function.

But if the key is known, inputs generating state collisions can be easily crafted. So, we should make that clear somewhere, probably in the security considerations.

**Comment by samuel-lucas6** [comment]
I agree. That's a sensible place to put it.
