### ISSUE TITLE
Require SHA512 for the variants with 256-bit security?

### ISSUE THREAD

**Issue by jedisct1** [cfrg/draft-irtf-cfrg-aegis-aead#20]
It's 2am and I need to get some sleep before reading this, but @emanjon just dropped this:

https://eprint.iacr.org/2023/913.pdf

For AEGIS-256X, this is not an issue, as the IANA request hasn't been made yet.

For `TLS_AEGIS_256_SHA384`, I don't know if the suite name can be updated (that would be a breaking change for existing implementations, but this is fine as the document is still a draft), or if we should ask for a new one.

**Comment by samuel-lucas6** [comment]
I haven't read the full paper yet, but it does seem like that should be swapped. Guess [Sabrina Tanamal](https://mailarchive.ietf.org/arch/msg/tls-reg-review/NTUFnKVAqI832Jt-fe-HzT-xaJw/) who assigned that needs to be contacted/asked.

**Comment by jedisct1** [comment]
I reached out to Sabrina. Waiting for her response.

**Comment by jedisct1** [comment]
IANA updated the entry: https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-4

I'm going to inform/update existing implementations.
