### ISSUE TITLE
Document a way to commit to everything

### ISSUE THREAD

**Issue by jedisct1** [cfrg/draft-irtf-cfrg-aegis-aead#3]
Due to the way the AD is absorbed, the differences of key and nonce can be canceled out, leading to a state collision. This is why AEGIS isn't fully committing.

Something to explore is slower absorption, giving control only on half an AES word before the permutation:

AEGIS-256:

```
Absorb(ai):
    t0, t1 = Split(ai, 64)
    Update(ZeroPad(t0, 128))
    Update(ZeroPad(t1, 128))
```

AEGIS-128L:

```
Absorb(ai):
    t0, t1, t2, t3 = Split(ai, 64)
    Update(ZeroPad(t0, 128), ZeroPad(t1, 128))
    Update(ZeroPad(t2, 128), ZeroPad(t3, 128))
```

Eliminating the differences in just a single word would then require up to 2^64 input blocks, and differences would be reintroduced on the following state updates. 

Associated data is usually pretty short, so performance impact should be acceptable.

A more conservative way that doesn't require a different absorption procedure is to hash the AD, i.e. recommend using:

```
Encrypt(msg, H(ad), key, nonce)
```

instead of

```
Encrypt(msg, ad, key, nonce)
```

As long as `H` is preimage-resistant, finding associated data that cancel the key and nonce differences becomes impractical.

Sure, hashing has a cost, and the security level can degrade to the one of the hash function. But only the AD has to be hashed, it doesn't require changes to the specification nor implementations, and that can be documented as a simple recommendation for protocols that require a fully committing scheme.

**Comment by samuel-lucas6** [comment]
> Something to explore is slower absorption, giving control only on half an AES word before the permutation

Whilst I like this idea, isn't it too late to make such a change?

> A more conservative way that doesn't require a different absorption procedure is to hash the AD

This seems worth mentioning. Security Considerations section?

**Comment by jedisct1** [comment]
> Whilst I like this idea, isn't it too late to make such a change?

It is.

We can document this as optionally calling `Encrypt(msg, Expand(ad), key, nonce)` for protocols requiring full commitment, and define `Expand(ad)` as something like:

```
a = Split(ZeroPad(ad, 128), 64)
b = {}
for x in a:
   b = b || ZeroPad(x, 128)
return b 
```

i.e. insert a 64 bit empty block every 64 bit ad block.

But this is not ideal, and looks like a last-minute patch. Also requires a publication to refer to.

Hashing the AD is not as efficient, but boring in a good way.

> Security Considerations section?

Looks like right place for it.
