### ISSUE TITLE
Updated paper for AEGIS key commitment

### ISSUE THREAD

**Issue by samuel-lucas6** [cfrg/draft-irtf-cfrg-aegis-aead#41]
Came across [this](https://tosc.iacr.org/index.php/ToSC/article/view/11404/) paper the other day, which seems to be an update of the [preprint](https://eprint.iacr.org/2023/1495) we reference, although the updates are more about other algorithms. Do you think it's worth changing the reference and/or updating the Acknowledgments?

**Comment by jedisct1** [comment]
Yes, this is the paper that was presented at FSE. I had an opportunity to chat with Mostafizar.

The results and methodology are the same as the one we reference, except that it expands to other algorithms.

So I'm not sure that it's worth changing the link. The current one has the advantage of being more focused.

**Comment by samuel-lucas6** [comment]
Cool, I did wonder if you'd say that. I'll close this then.
