### ISSUE TITLE
Addressing Scott Fluhrer's Review

### ISSUE THREAD

**Issue by samuel-lucas6** [cfrg/draft-irtf-cfrg-aegis-aead#50]
The full version can be found [here](https://mailarchive.ietf.org/arch/msg/cfrg/ikGi2zb6CmWyQIVhuo8QR_GrOsA/).

> You state that AEGIS-128L has “a better security margin” than AEGIS-128.  Citation?  Against what attack(s)?  A bigger state doesn’t necessarily translate into a bigger security margin, and AEGIS-128 does 5 AES rounds per plaintext block, while AEGIS-128L does 4 – does the decrease in the number of rounds decrease the security margin (I don’t know, but it’s certainly not obvious either way)

There's already a citation in that sentence. From Ctrl+F, it says `the successful attack on 5-round AEGIS-128 cannot be applied to 5-round AEGIS-128L`. Do we want to cite any other papers?

I'm not sure we should start naming attacks as this is the Introduction.

> You state that “The AEGIS cipher family offers performance that significantly exceeds that of AES-GCM with hardware support” – is this true?  Or, are you talking about a software implementation with “hardware support” (e.g. VAES).  I believe that, for pure hardware, AES-GCM is significantly faster (because of the pipelinability and the parallelizability)

Again, there's a citation for this claim, although we could perhaps also cite your parallel modes paper. I think saying `with hardware support` rather than `hardware implementation` is clear enough, although I suppose we could also mention the performance for a hardware implementation separately. From a quick glance at a few papers, I'm unsure which is faster in hardware as some say GCM is slower and one seems to suggest it's faster, not that I know anything about this topic.

> You state “… an AEGIS key is not required after the setup phase”.  However, when you look at the encrypt and decrypt procedures, they use the key as an input to the internal Init function.

The Authenticated Encryption/Decryption sections are being discussed here. We could rephrase `after the setup phase` to `after initialization` or `after calling Init()/the initialization function`.

> Are the 256 bit tag lengths your own innovation?  They do not appear in the Caesar submission.  It’s also unclear to me in what scenario a ‘longer than 128 bit tag’ would be required – are you worried about collisions?  I also note that for AEGIS-256, you can compute the 16 byte tag by xor’ing the two halves of the 32 byte tag (but the same does not apply to AEGIS-128L).  I don’t see how that leads to a weakness – it does look odd.

Given this wasn't in the CAESAR submission, this probably does warrant further explanation, like design rationale and references in Security Guarantees. However, we say why a 256-bit tag is important when discussing commitment in the Introduction.

> AESRound – you might want to define that more explicitly; I don’t know if it’s obvious you mean to perform the SubBytes, Shiftrows and MixColumn operations on ‘in’ and then xor in ‘rk’.  For an internal function as fundamental (and nontrivial) as this, you might want to have several descriptions.

I don't think this is a problem. We've basically said that and with a citation.

> You mention about security in the “Q1 model”.  One suggestion (not a requirement for this review) would be to spell out what that “Q1 model” is; that is, an attack model where the attacker has access to a Quantum Computer, but is limited to classical (nonquantum) communications to the systems under attack.  I suspect that most implementors wouldn’t don’t know what “Q1” is.

I think this is a good idea if it can be done in a sentence or two.

> I did like the test vectors, the test vectors for the subcomponents makes things more straightforward.  Just one comment: for the 128L Update text vector, you might want to make M0 and M1 different (to catch cases where the implementation uses the wrong one).

I presume we can do this without much trouble.

**Comment by jedisct1** [comment]
> You state that AEGIS-128L has “a better security margin” than AEGIS-128. Citation? Against what attack(s)? A bigger state doesn’t necessarily translate into a bigger security margin, and AEGIS-128 does 5 AES rounds per plaintext block, while AEGIS-128L does 4 – does the decrease in the number of rounds decrease the security margin (I don’t know, but it’s certainly not obvious either way)

The bigger state and more complex linear layer affects the security of the initialization phase, as well as the key stream.

Keystream:
- https://tosc.iacr.org/index.php/ToSC/article/view/8468/8034 shows that linear biases are smaller for 128L than 128.

Initialization:
-  https://academic.oup.com/comjnl/article-abstract/65/8/2221/6280579 shows that 128L is more secure than 128 against guess-and-determine attacks
- https://tosc.iacr.org/index.php/ToSC/article/view/8907/8483 shows that 128L has better integral properties. Key recovery on 5 rounds (out of 10) i128 is demonstrated, but fails with the same number of rounds (also out of 10) for 128L.
- https://ietresearch.onlinelibrary.wiley.com/doi/10.1049/ise2.12109 shows that 128L is secure against differential attacks after 3 rounds (out of 10) instead of 4 rounds for 128 (out of 10).

The fact that input blocks are passing into 4 AES rounds (for 128L) instead of 5 (for 128) mostly affect integrity, where  https://link.springer.com/chapter/10.1007/978-981-97-7737-2_1 shows that 128 has slightly better resistance against forgery. But I don't think this falls into the "security margin" category as much as the number of rounds required for security vs total number of rounds in initialization, especially given the huge margin with respect to the 128-bit security against forgery we claim in the document.

**Comment by jedisct1** [comment]
> You state that “The AEGIS cipher family offers performance that significantly exceeds that of AES-GCM with hardware support” – is this true? Or, are you talking about a software implementation with “hardware support” (e.g. VAES). I believe that, for pure hardware, AES-GCM is significantly faster (because of the pipelinability and the parallelizability)

Hardware implementations are hard to compare for algorithms that can be parallelized, because the can perform very differently depending on the available area. Given the same area, I don't know which one would be more efficient. 

In https://www.researchgate.net/publication/283542585_Efficient_Hardware_Accelerator_for_AEGIS-128_Authenticated_Encryption they describe large-area AEGIS as much faster than AES-GCM, but the benchmarked AES-GCM implementation may process blocks sequentially.
Maybe we could replace "with hardware support" with "on CPUs with AES instructions"?

**Comment by jedisct1** [comment]
> The Authenticated Encryption/Decryption sections are being discussed here. We could rephrase after the setup phase to after initialization or after calling Init()/the initialization function.

"setup phase" was used to avoid a repetition, but if this is confusing, yes, we can explicitly name the function.

**Comment by jedisct1** [comment]
> Are the 256 bit tag lengths your own innovation? They do not appear in the Caesar submission. It’s also unclear to me in what scenario a ‘longer than 128 bit tag’ would be required – are you worried about collisions? I also note that for AEGIS-256, you can compute the 16 byte tag by xor’ing the two halves of the 32 byte tag (but the same does not apply to AEGIS-128L). I don’t see how that leads to a weakness – it does look odd.

Collisions, better key commitment, more useful as a MAC, and https://link.springer.com/chapter/10.1007/978-981-97-7737-2_1 shows that AEGIS256 can claim 256-bit forgery security by diﬀerential attacks (and 216-bit security for 128L) with a 256-bit tag.

The finalization rounds provides full diffusion, so arbitrary words could be used to compute tags. The designers used a linear combination, which is akin to a sum of PRFs, only to improve randomness. We construct 256-bit tags exactly the same way.

Regarding the fact that a 128 tag can be computed by xoring the halves of a 256 bit tag : in [section 9.1.1](https://www.ietf.org/archive/id/draft-irtf-cfrg-aegis-aead-12.html#section-9.1.1), we have: "All AEGIS variants MUST be used in a nonce-respecting setting: for a given key, a nonce MUST only be used once, **even with different tag lengths**", which covers this.

**Comment by jedisct1** [comment]
>> AESRound – you might want to define that more explicitly; I don’t know if it’s obvious you mean to perform the SubBytes, Shiftrows and MixColumn operations on ‘in’ and then xor in ‘rk’. For an internal function as fundamental (and nontrivial) as this, you might want to have several descriptions.

> I don't think this is a problem. We've basically said that and with a citation.

In the primitives, we explicitly say "which is the composition of the SubBytes, ShiftRows, MixColums and AddRoundKey transformations", so I also don't think we could be more explicit. This has also been clear to all implementers so far.

**Comment by jedisct1** [comment]
> > You mention about security in the “Q1 model”. One suggestion (not a requirement for this review) would be to spell out what that “Q1 model” is; that is, an attack model where the attacker has access to a Quantum Computer, but is limited to classical (nonquantum) communications to the systems under attack. I suspect that most implementors wouldn’t don’t know what “Q1” is.

> I think this is a good idea if it can be done in a sentence or two.

Sure.

> > I did like the test vectors, the test vectors for the subcomponents makes things more straightforward. Just one comment: for the 128L Update text vector, you might want to make M0 and M1 different (to catch cases where the implementation uses the wrong one).

> I presume we can do this without much trouble.

Indeed. I'll do that.

**Comment by samuel-lucas6** [comment]
> The bigger state and more complex linear layer affects the security of the initialization phase, as well as the key stream.

Thanks for the detailed reply. How do you feel about citing more papers for the `better security margin` claim? Citing all of them may be a bit over the top though, especially when we have references in the Security Guarantees section.

> In https://www.researchgate.net/publication/283542585_Efficient_Hardware_Accelerator_for_AEGIS-128_Authenticated_Encryption they describe large-area AEGIS as much faster than AES-GCM, but the benchmarked AES-GCM implementation may process blocks sequentially.

Yeah, that was one paper I saw. Happy to leave that then.

> Maybe we could replace "with hardware support" with "on CPUs with AES instructions"?

That sounds good. Perhaps `software implementations` should be reworded too, like `Similarly, software implementations not using AES instructions can also be faster`.

> "setup phase" was used to avoid a repetition, but if this is confusing, yes, we can explicitly name the function.

I'll do a PR for that.

> The finalization rounds provides full diffusion, so arbitrary words could be used to compute tags. The designers used a linear combination, which is akin to a sum of PRFs, only to improve randomness. We construct 256-bit tags exactly the same way.

Do you think it's worth a sentence saying that 256-bit tags weren't in the CAESAR submission but have been constructed in the same fashion? I remember Rocca-S doing the same. We could maybe cite that 256-bit tag paper.

**Comment by samuel-lucas6** [comment]
I believe we've addressed all of his comments so going to close this.
