### ISSUE TITLE
Addressing Gilles feedback

### ISSUE THREAD

**Issue by jedisct1** [cfrg/draft-irtf-cfrg-aegis-aead#59]
Quoting Gilles VAN ASSCHE:

> I have one comment on the parallel instances AEGIS-{128,256}X. These instances internally call AEGIS-128L and AEGIS-256, respectively, with parts of the plaintext and associated data (AD), so that they can be computed in parallel branches. The resulting tag is obtained simply by XORing the tags coming from the different branches. Although the draft clearly mandates a nonce-respecting setting, when AEGIS-{128,256}X is used solely to compute a MAC, the user may be tempted to ignore this and fix the nonce. In a nonce-less MAC setting, this leads to a forgery attack: one obtains the tags for XY, ZY and XT (with X, Z being plaintext or AD in one branch, and Y, T in another branch) and then computes the tag for ZT as tag(ZT)=tag(XY)^tag(ZY)^tag(XT).
>
> Section 9 warns about the consequences of nonce reuse for encryption, but not for authentication. Also, the third paragraph of Section 9.3 suggests that one can trade nonce uniqueness for AD uniqueness, but that does not work for authentication with AEGIS-{128,256}X.
> 
> So, this probably deserves some warnings or clarifications in the text before the draft is published.

We indeed need to emphasize the importance of the nonce for authentication.

Section 9.3 contains:
"Encrypting the same message with the same key and nonce but different associated data generates distinct ciphertexts that do not reveal any additional information about the message."

This is true and nice, but the practical importance of this is limited. And as Gilles pointed out, it may suggest that one can trade nonce uniqueness for AD uniqueness. Maybe we should remove that sentence?

Regarding usage as a MAC. Section 9.1.4 is currently very sparse and misleading. We can remove it, and emphasize that AEGIS must not be used as a hash function elsewhere.

However, usage with a fixed nonce is legitimate, and there are already applications doing this in the wild.

So, another thing we could do is expand section 9.1.4.

First, we can introduce the AEGIS128L-MAC, AEGIS128X-MAC, AEGIS256L-MAC, AEGIS256X-MAC names, so that applications can refer to AEGIS being used in that context consistently.

AEGIS128L-MAC and AEGIS256-MAC are exactly AEGIS128L and AEGIS256 with an empty input message.

For the parallel variants, there are simple ways to safely support nonce reuse (for the MAC use case only):

> the value (tag[0] || tag[1] || ... || tag[D-1]) can be used as input to a non-parallel variant to compute the final MAC.
>
> Or equivalently:
>
> ```sh
> # compute tags { tag[0], tag[1], ... tag[D-1] } as usual, then:
> Absorb(Pad(tag[1], R) || ... || Pad(tag[D-1], R)) # absorb tags from states 1..D-1 into state 0
> t = ZeroPad(LE64(tag_length) || LE64(D), R) # context separation is free
> Repeat(7, Update(t, t))
> # compute final tag from V[0] blocks as usual
> ```

I implemented this, and the changes were trivial.

But that requires defining alternative Finalization functions in section 9.1.4. Although it can be concise, and would not touch any other sections in the document, it can clearly feel a bit like a last-minute addition.

The easiest thing to do would be to only emphasize the importance of nonces, and not deal at all with nonce-less authentication. However, defining proper MAC functions would better deserve the users. But the draft may be too far in the process to make non-editorial changes. OTOH, the 256-bit versions of TurboSHAKE and KT were also added at the last minute, so this is doable.

What do you think @samuel-lucas6 ?

**Comment by jedisct1** [comment]
Implementation-friendly example `FinalizeMac` function for 128X:

```sh
t = {}
u = LE64(data_len_bits) || LE64(0)
for i in 0..D:
    t = t || (V[2,i] ^ u)

Repeat(7, Update(t, t))

tags = {}
if tag_length == 16: # 128 bits
    for i in 0..D:   # tag from state 0 is included
        tags = tags || (V[0,i] ^ V[1,i] ^ V[2,i] ^ V[3,i] ^ V[4,i] ^ V[5,i] ^ V[6,i])

else:                # 256 bits
    for i in 1..D:   # tag from state 0 is skipped
        tags = tags || (V[0,i] ^ V[1,i] ^ V[2,i] ^ V[3,i]) || (V[4,i] ^ V[5,i] ^ V[6,i] ^ V[7,i])

if D > 1:
    # Absorb tags into state 0; other states are not used anymore
    for ti in Split(tags, 256):
        Absorb(ZeroPad(ti, R))

    u = LE64(tag_length) || LE64(D)
    t = ZeroPad(V[2,0] ^ u, R)
    Repeat(7, Update(t, t))

if tag_length == 16: # 128 bits
    tag = V[0,0] ^ V[1,0] ^ V[2,0] ^ V[3,0] ^ V[4,0] ^ V[5,0] ^ V[6,0]
else:                # 256 bits
    tag = (V[0,0] ^ V[1,0] ^ V[2,0] ^ V[3,0]) || (V[4,0] ^ V[5,0] ^ V[6,0] ^ V[7,0])
```

For 256X:

```sh
t = {}
u = LE64(data_len_bits) || LE64(0)
for i in 0..D:
    t = t || (V[3,i] ^ u)

Repeat(7, Update(t))

tags = {}
if tag_length == 16: # 128 bits
    for i in 1..D:   # tag from state 0 is skipped
        tags = tags || (V[0,i] ^ V[1,i] ^ V[2,i] ^ V[3,i] ^ V[4,i] ^ V[5,i])

else:                # 256 bits
    for i in 1..D:   # tag from state 0 is skipped
        tags = tags || (V[0,i] ^ V[1,i] ^ V[2,i]) || (V[3,i] ^ V[4,i] ^ V[5,i])

if D > 1:
    # Absorb tags into state 0; other states are not used anymore
    for ti in Split(tags, 128):
        Absorb(ZeroPad(ti, R))

    u = LE64(tag_length) || LE64(D)
    t = ZeroPad(V[3,0] ^ u, R)
    Repeat(7, Update(t))

if tag_length == 16: # 128 bits
    tag = V[0,0] ^ V[1,0] ^ V[2,0] ^ V[3,0] ^ V[4,0] ^ V[5,0] ^ V[6,0]
else:                # 256 bits
    tag = (V[0,0] ^ V[1,0] ^ V[2,0] ^ V[3,0]) || (V[4,0] ^ V[5,0] ^ V[6,0] ^ V[7,0])
```

**Comment by jedisct1** [comment]
So, that would expand section 9.1.4 quite a bit, in addition to the test vectors.

**Comment by samuel-lucas6** [comment]
Thank you for all these PRs/issues. I think the related PRs are appropriate changes.

I think naming them is a good idea. My concern is that Section 9.1.4 is in the Security Considerations, which probably shouldn't be specifying something like this. It might be better as a dedicated section like `AEGIS as a Message Authentication Code`, and then you could perhaps remove Section 9.1.4. The other issue is indeed more variants/test vectors, but I suppose there's nothing that can really be done about this. Different Finalization functions is fine by me as long as it doesn't cause confusion.

**Comment by samuel-lucas6** [comment]
Also, we need to remember to thank Chris and Gilles in the Acknowledgments.

**Comment by jedisct1** [comment]
> I think naming them is a good idea. My concern is that Section 9.1.4 is in the Security Considerations, which probably shouldn't be specifying something like this. It might be better as a dedicated section like `AEGIS as a Message Authentication Code`, and then you could perhaps remove Section 9.1.4. The other issue is indeed more variants/test vectors, but I suppose there's nothing that can really be done about this. Different Finalization functions is fine by me as long as it doesn't cause confusion.

Section 9.1.4 is called "Other Uses`, but only covers usage as a MAC. So, yes, it makes total sense to convert it into a section explicitly called `AEGIS as a Message Authentication Code`.
