### ISSUE TITLE
Addressing Chris feedback

### ISSUE THREAD

**Issue by jedisct1** [cfrg/draft-irtf-cfrg-aegis-aead#60]
> Section 3.2: "The decrypted message MUST be overwritten with zeros."
Proposed change: "The decrypted message MUST be overwritten with zeros
before being returned."
>
> Accounts for implementations where the message and ciphertext don't overlap and the function either returns the message or throws an exception. Overwriting is unnecessary if the value is no longer accessible after the function returns.
> 
> Section 5.1: "The rate is 2 * 128 * D bits."
> Proposed change: "256 * D bits."
> 
> The expanded form is unnecessary and, in my opinion, less clear.
> 
> Section 5.4.2: "but absorbs R (2 * 128 * D) bits at once."
> Proposed change: "but absorbs R (= 256 * D) bits at once."
>
> Clarifies that R is equal to 256 * D and not interpreted as R * 2 * 128 * D

I don't have strong feelings about 2*128 vs 256.

Regarding the message buffer that must be overwritten on verification failure, we discussed this a while back. But it was about using MUST NOT vs SHOULD NOT. 
I like the suggestion, as it still makes it clear that the buffer MUST be zeroed when relevant.

**Comment by samuel-lucas6** [comment]
> Regarding the message buffer that must be overwritten on verification failure, we discussed this a while back. But it was about using MUST NOT vs SHOULD NOT.
> I like the suggestion, as it still makes it clear that the buffer MUST be zeroed when relevant.

I'm happy with that change as well. I guess you could also say `If possible in your programming language, ...`, but that's somewhat common sense.

> I don't have strong feelings about 2*128 vs 256.

I think this should be 256 as it matches how AEGIS-128L is described.

**Comment by jedisct1** [comment]
> I'm happy with that change as well. I guess you could also say `If possible in your programming language, ...`, but that's somewhat common sense.

Yeah, that's common sense. And even in a given programming language, different calling conventions can be implemented.

> 
> > I don't have strong feelings about 2*128 vs 256.
> 
> I think this should be 256 as it matches how AEGIS-128L is described.

Ok.
