### ISSUE TITLE
Add implementation status

### ISSUE THREAD

**Issue by jedisct1** [cfrg/draft-irtf-cfrg-aegis-aead#7]
https://www.rfc-editor.org/rfc/rfc7942 (also recommended in https://www.ietf.org/archive/id/draft-eckel-edm-find-code-02.html) suggests adding an "Implementation status" section, that will eventually be removed before the RFC is published.

Even though Datatracker links this repository for discussions, finding available implementations, including the reference ones, may not be obvious.

Maybe we should add an "Implementation status" section, that either includes a copy of the table with have in the `README.md` file here, or links to it.

**Comment by jedisct1** [comment]
`draft-eckel-edm-find-code` mentions:

> A GitHub repository is associated with the I-D using the `github_repo` tag.

We should use that to add a link to this repository. I looked really hard, but didn't find how to add that tag on Datatracker. How to do this?

/cc @eckelcu

**Comment by samuel-lucas6** [comment]
> Maybe we should add an "Implementation status" section, they either includes a copy of the table with have in the README.md file here, or links to it.

I think it would be better to link to the table since that will be kept up to date rather than new drafts. The amount of information this RFC is talking about would also make for a long section.

We should probably add `This note is to be removed before publishing as an RFC.` like in the `Discussion Venues` so we hopefully don't forget to remove it.

**Comment by eckelcu** [comment]
> `draft-eckel-edm-find-code` mentions:
> 
> > A GitHub repository is associated with the I-D using the `github_repo` tag.
> 
> We should use that to add a link to this repository. I looked really hard, but didn't find how to add that tag on Datatracker. How to do this?
> 
> /cc @eckelcu

draft authors are able to add these tags for individual drafts. Once they become working group drafts, only the WG chairs can add them.

**Comment by jedisct1** [comment]
Thank you @eckelcu !

That explains it.
