### ISSUE TITLE
Downloadable test vectors

### ISSUE THREAD

**Issue by jedisct1** [cfrg/draft-irtf-cfrg-aegis-aead#9]
The document includes test vectors that are easy to parse.

But maybe it would be useful to also offer them as files that can be downloaded from this repository, in various formats (KAT, JSON, etc.)

Similar to the implementation table, the link would have to be removed before the RFC publication.

**Comment by samuel-lucas6** [comment]
That's a good idea. How would the 'verification failed' ones be separated? Would the different AEGIS-128/256X2 vs 4 test vectors go in the same file?

**Comment by jedisct1** [comment]
The Project Wycheproof test vectors include a "result" property (`valid`/`invalid`). At least for JSON, we can adopt their conventions.

And once file per variant is probably more convenient.
